### ISSUE TITLE
Multiple Small Objective-Specific Issues with Ticking (add more if need be)

### ISSUE THREAD

**Issue by Robin3150** [rhelmot/CelesteBingoClient#13]
Complete 3 A-Sides is tickable after only 2 A-sides, presumably because Prologue is counted as an A-side.
Get the Orb in PICO-8 is tickable after reaching 2300M without grabbing the orb.

**Comment by Robin3150** [comment]
Dashless objectives are cheesable by gettinga  free dash (see attached clip). After that dash is used (or the player dies), dashless continues as proper. Crossing room 1 is cheesable in the same way. Github won't let me upload a video long enough to see the ending, but the objective can be claimed.

https://user-images.githubusercontent.com/69094449/108903838-c3f04580-75eb-11eb-9384-33cb187adc7c.mp4

**Comment by rhelmot** [comment]
Fixed. Issues are cheap, feel free to open another one if you find more :)
