### ISSUE TITLE
Complete 2 Chapters Grabless doesn't trigger disable grabbing at any checkpoint (especially 1a or 2a)

### ISSUE THREAD

**Issue by Robin3150** [rhelmot/CelesteBingoClient#20]
Not sure whether it'd be better to have 2 chapters grabless let you disable grabbing at any checkpoint, or only in 1a/2a, or what. In any case, it should do so somewhere.

**Comment by rhelmot** [comment]
oh yeah! I actually already put in the work for how this should be implemented but I never wired it up to make it actually happen. Should be fixed now.
