### ISSUE TITLE
Grabless disable trigger being located at mountain sign leads to awkward placement

### ISSUE THREAD

**Issue by Robin3150** [rhelmot/CelesteBingoClient#21]
Especially in the cases of Presidential Suite, Cliff Face, Unraveling, and Lake, knowing to reach the mountain sign to activate grabless isn't apparently obvious, especially since the load into map points don't actually pass that sign. If grabless triggers were located at spawnpoints that would be better; if they were located customly to be at any point before the room's difficulty begins, that would be even better (though a lot more difficult, I imagine).

**Comment by Retrisma** [comment]
Also for Start of 6A, the grabless start is on the left side of the screen, and spawn is on the right

**Comment by rhelmot** [comment]
I've changed it so that it will also count the nearest spawnpoint to the mountain icon, and also added special cases for 6a start and lake. I'll do another release tonight, let me know if there are still problems!
