### ISSUE TITLE
Get (x) berries in pico-8 and Read diary in elevator shaft dont get recognized as achieved

### ISSUE THREAD

**Issue by true-gen** [rhelmot/CelesteBingoClient#22]
As the title says
![yPxtvoK](https://user-images.githubusercontent.com/77693065/109052418-80710680-76d3-11eb-8fd3-1868442d7a75.png)
![gvBydvI](https://user-images.githubusercontent.com/77693065/109052430-849d2400-76d3-11eb-9233-f9a6352dbcdf.png)

**Comment by rhelmot** [comment]
I found the bug behind the pico berries, and that's fixed, but I wasn't able to reproduce the diary problem. 
![image](https://user-images.githubusercontent.com/2498805/109091129-71895480-76d1-11eb-9e7c-9a61a3590420.png)

**Comment by true-gen** [comment]
![image](https://user-images.githubusercontent.com/77693065/109219772-f64aa000-77af-11eb-8b88-e02441c797f5.png)
![izfKyDE](https://user-images.githubusercontent.com/77693065/109219792-ff3b7180-77af-11eb-9475-2d4157d55cb8.png)
![e86IWU2](https://user-images.githubusercontent.com/77693065/109219849-137f6e80-77b0-11eb-8287-fa451e4697f2.png)

**Comment by rhelmot** [comment]
Can you try reading the diary in elevator shaft again in 0.0.8? I think I figured out what's wrong.

**Comment by Retrisma** [comment]
As of 0.0.9, reading the diary ticks off as intended.
