### ISSUE TITLE
Objectives tick themselves without any input from the player

### ISSUE THREAD

**Issue by true-gen** [rhelmot/CelesteBingoClient#24]
Scenarios I have seen this happen:
Enabling grabless/jumpless/dashless after finishing a relevant objective.
Checking the board after finishing an all collectibles objective.
![7YqrTZv](https://user-images.githubusercontent.com/77693065/109055796-879a1380-76d7-11eb-8d7a-fbe09c597b70.png)
![vwPpI9r](https://user-images.githubusercontent.com/77693065/109055800-88cb4080-76d7-11eb-9450-c136d0ba4b8e.png)

**Comment by true-gen** [comment]
Bug seems to be relating to pressing enter

https://youtu.be/eLKAJsmsNkw

https://youtu.be/JKBQfukTGPU

**Comment by rhelmot** [comment]
![image](https://user-images.githubusercontent.com/2498805/109224398-1d39af80-7779-11eb-8e7d-b42586c531cc.png)

should there be a different default binding?
