### ISSUE TITLE
If a new card is generated, the new card does not need to be revealed by pressing confirm

### ISSUE THREAD

**Issue by true-gen** [rhelmot/CelesteBingoClient#28]

**Comment by rhelmot** [comment]
are you sure? https://streamable.com/o7983a

**Comment by Retrisma** [comment]
As of 0.0.9, hidden cards must be revealed by confirm. However, sometimes "x is now claimable" messages show up when new cards are made, spoiling some objectives. Maybe those messages should only show up if the card is revealed?
