### ISSUE TITLE
Feature Request: Add settings to improve menu toggle UI

### ISSUE THREAD

**Issue by Robin3150** [rhelmot/CelesteBingoClient#29]
There could be a setting to have the menu toggle button be single-press toggleable instead of holdable, to help keyboard players. It'd probably have to automatically disappear if you hit menu trigger.

Also there could be a setting to change the UI size of this toggle and/or make sure it stays in a corner. Generally the top-right corner is the least crowded for this purpose, as it wouldn't then cover things like file time or mountain savepoint appearances, etc.

**Comment by rhelmot** [comment]
1) Done, try out the new release!
2) I added an option to control the opacity when you're just viewing the card and made it so that the claim/variants menu doesn't display in that mode either. Let me know if you think this is insufficient.
