### ISSUE TITLE
Read Poem in 2a no longer being triggered in 0.0.6

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#31]

**Comment by rhelmot** [comment]
![Screenshot from 2021-02-27 21-05-17](https://user-images.githubusercontent.com/2498805/109407724-7142c080-7940-11eb-86b7-fe488e0720f0.png)

Can you try again? Is there anything special you did during or before connecting this round?

**Comment by Retrisma** [comment]
I tried again, and it still doesn't tick off, even on 0.0.7. I didn't do anything special connecting. In addition, the Theo cutscene in 5a is also not ticking off for me.

**Comment by rhelmot** [comment]
Can you try with 0.0.8? I think I figured out what's wrong.

**Comment by Retrisma** [comment]
Reading the poem & all Theo cutscenes are ticking off for me in 0.0.9, but Talk to Theo in Search doesn't.

**Comment by rhelmot** [comment]
Ohhhhhh this one is just me being an idiot. will be fixed in next release.
