### ISSUE TITLE
Reach Rock Bottom (6a/6b Checkpoint) checks off after unlocking Reflection subchapter in 6b

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#32]

**Comment by rhelmot** [comment]
omg haha this is such a silly bug. basically it's checking whether you have 4 checkpoints in 6a OR two checkpoints in 6b but the way it does this it will count a combination of partial progress toward both of them as the whole objective. very silly. it's fixed now. I'll put out a new version in the next few hours.
