### ISSUE TITLE
When claim assist is on, pressing 'confirm' even while in-game marks off objectives.

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#33]
This means that it's impossible to delay objectives while claim assist is on. It also means that if you spam confirm, the objective can be marked off multiple times. Incidentally, though, it's pretty convenient for blackout.

**Comment by rhelmot** [comment]
Can you try to reproduce this with BingoUI disabled? Or equivalently, can you rebind Quick Claim away from the enter key? I think what is happening is that BingoUI's "press confirm to skip tally", which rebinds confirm to be equivalent to enter, is  triggering the quick claim functionality.

**Comment by Retrisma** [comment]
Rebinding Quick Claim away from Enter worked.
