### ISSUE TITLE
Game crashes when beginning a new file after connecting to Bingosync

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#7]
Connecting to the bingo servers works fine, but the game crashes when I select Begin. Here is the error log.

[error_log.txt](https://github.com/rhelmot/CelesteBingoClient/files/6029342/error_log.txt)
Edit: uploaded wrong thing

I am on Everest 1.2637.0-azure, and XNA framework

Thanks for making this! Excited to use it in games

**Comment by rhelmot** [comment]
This is a bug where the game can't handle boards that have summit gem objectives on them. I pushed a fix, it'll be in the next release.
